---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
data:
  # Replace these base64 encoded values with your actual credentials
  mongo-root-username: cm9vdHVzZXI=  # rootuser
  mongo-root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  mongo-db-name: bXlkYXRhYmFzZQ==  # mydatabase
  mongo-db-username: ZGJ1c2Vy  # dbuser
  mongo-db-password: ZGJwYXNzd29yZA==  # dbpassword