---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccountName }}
  labels:
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccountName }}
  labels:
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    