---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.serviceName }}
  labels:
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  selector:
    app: {{ .Values.database.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.servicePort }}
      targetPort: {{ .Values.database.image.containerPort }} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.frontend.serviceName }}
  labels:
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  selector:
    app: {{ $.Values.frontend.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.image.containerPort }} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.backend.serviceName }}
  labels:
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  selector:
    app: {{ .Values.backend.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.image.containerPort }}    